---
# tasks file for mysql

- name: Install MySQL
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-mysqldb
    - mysql-server
    - libdbd-mysql
    - mysql-client

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: true

- name: Set MySQL root password
  mysql_user:
    login_user: root
    login_password: ""
    name: root
    password: "{{ mysql_root_password }}"

- name: Copy MySQL Credentials
  template:
    src: templates/.my.cnf
    dest: ~/.my.cnf
    owner: root
    mode: 0600

- name: Create MySQL app user
  mysql_user:
    name: "{{ mysql_app_user }}"
    password: "{{ mysql_app_password }}"
    host: "%"
