---
# tasks file for uwsgi

- name: Install Python Build
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - build-essential
    - python

- name: Install Pip
  easy_install:
    name: pip
    state: latest

- name: Install uWSGI
  pip:
    name: uwsgi
